package Recursion.RecursionOnStrings;
import java.util.Scanner;
import java.util.ArrayList;

// Given a String, write a method to return all it's sub-sequences in
// an arraylist. A String is a subsequence of a given string that is
// generated by deleting some character of a given string without
// changing its order
public class ReturnSSQ {                // space complexity : 2^n
    static ArrayList<String> getSSQ(String s){
        ArrayList<String> ans = new ArrayList<>();
        // Base Case
        if(s.isEmpty()){
            ans.add("");
            return ans;
        }

        char curr = s.charAt(0);
        ArrayList<String> smallAns = getSSQ(s.substring(1));
        for(String ss : smallAns){
            ans.add(ss);
            ans.add(curr+ss);
        }
        return ans;
    }
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in) ;
        System.out.print("Enter a string : ");
        String s = sc.next();
        ArrayList<String> ans = getSSQ(s);
        System.out.println(ans);
    }
}
